In [ ]:
pip install jovian --upgrade

In [ ]:
python -m jovian clone aakashns/100-numpy-exercises 
cd 100-numpy-exercises

In [ ]:
conda create -n 100-numpy-exercises jupyter

In [ ]:
conda activate 100-numpy-exercises
jupyter notebook

In [2]:
import numpy as np

In [16]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\psath\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [4]:
print(np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/psath/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/psath/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/psath/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/psath/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/psath/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/psath/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/psath/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/psath/anaconda3\\Library\\include']
None


In [20]:
 a  = np.array(10)

In [22]:
a

array(10)

In [15]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [24]:
 a = np.zeros(10)

In [25]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
a[4] = 1

In [27]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [29]:
b = np.array([10:])

SyntaxError: invalid syntax (Temp/ipykernel_10828/1716915136.py, line 1)

In [35]:
a  =np.array([[1, 2, 3,4],
             [2,34,5]])

C:\Users\psath\AppData\Local\Temp/ipykernel_10828/3809459243.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a  =np.array([[1, 2, 3,4],


In [34]:
a.shape

(2,)