In [41]:
import os


In [42]:
import urllib.request

In [43]:
os.listdir()

['.ipynb_checkpoints',
 '.jovianrc',
 '100 Exercises.ipynb',
 'Adobe Photoshop 2021.lnk',
 'AnalysingTabularDataPandas.ipynb',
 'bankLoan',
 'bankLoan.txt',
 'covid_database',
 'data',
 'emis1',
 'LearningDataScience.ipynb',
 'lerningDataSciences.ipynb',
 'Machine learning.ipynb',
 'movies.csv',
 'movies1.csv',
 'orphan.sh',
 'Removed Apps.html',
 'sample',
 'sathyappp']

In [44]:
bankLoan = open('bankLoan.txt')

In [45]:
lines = bankLoan.readlines()

In [46]:
lines

['amount,duration,rate,down_payment\n',
 '100000,36,0.08,20000\n',
 '200000,12,0.1,\n',
 '628400,120,0.12,100000\n',
 '4637400,240,0.06,\n',
 '42900,90,0.07,8900\n',
 '916000,16,0.13,\n',
 '45230,48,0.08,4300\n',
 '991360,99,0.08,\n',
 '423000,27,0.09,47200']

In [47]:
def prase_header(line):
    return line.strip().split(',')

In [48]:
prase_header(lines[0])

['amount', 'duration', 'rate', 'down_payment']

In [49]:
headers = prase_header(lines[0])

In [50]:
headers

['amount', 'duration', 'rate', 'down_payment']

In [51]:
def prase_values(line):
    values = []
    for value in line.strip().split(','):
        if(value ==''):
            values.append(0.0)
        else:
            values.append(float(value))
    return values

In [52]:
values = prase_values(lines[1])

In [53]:
values

[100000.0, 36.0, 0.08, 20000.0]

In [54]:
prase_values(lines[2])

[200000.0, 12.0, 0.1, 0.0]

In [55]:
def dict_val(headers, values):
    res = {}
    for header , val in zip(headers, values):
        res[header] = val
    return res

In [56]:
dict_val(headers, prase_values(lines[1]))

{'amount': 100000.0, 'duration': 36.0, 'rate': 0.08, 'down_payment': 20000.0}

In [57]:
def read_csv(path):
    res = []
    with open(path) as file:
        lines = file.readlines()
    headers = prase_header(lines[0])
    for line in lines[1 :] :
        res.append(dict_val(headers,prase_values( line)))
    return res
        

In [58]:
read_csv('bankLoan.txt')

[{'amount': 100000.0, 'duration': 36.0, 'rate': 0.08, 'down_payment': 20000.0},
 {'amount': 200000.0, 'duration': 12.0, 'rate': 0.1, 'down_payment': 0.0},
 {'amount': 628400.0,
  'duration': 120.0,
  'rate': 0.12,
  'down_payment': 100000.0},
 {'amount': 4637400.0, 'duration': 240.0, 'rate': 0.06, 'down_payment': 0.0},
 {'amount': 42900.0, 'duration': 90.0, 'rate': 0.07, 'down_payment': 8900.0},
 {'amount': 916000.0, 'duration': 16.0, 'rate': 0.13, 'down_payment': 0.0},
 {'amount': 45230.0, 'duration': 48.0, 'rate': 0.08, 'down_payment': 4300.0},
 {'amount': 991360.0, 'duration': 99.0, 'rate': 0.08, 'down_payment': 0.0},
 {'amount': 423000.0, 'duration': 27.0, 'rate': 0.09, 'down_payment': 47200.0}]

In [59]:
read_csv('bankLoan.txt')

[{'amount': 100000.0, 'duration': 36.0, 'rate': 0.08, 'down_payment': 20000.0},
 {'amount': 200000.0, 'duration': 12.0, 'rate': 0.1, 'down_payment': 0.0},
 {'amount': 628400.0,
  'duration': 120.0,
  'rate': 0.12,
  'down_payment': 100000.0},
 {'amount': 4637400.0, 'duration': 240.0, 'rate': 0.06, 'down_payment': 0.0},
 {'amount': 42900.0, 'duration': 90.0, 'rate': 0.07, 'down_payment': 8900.0},
 {'amount': 916000.0, 'duration': 16.0, 'rate': 0.13, 'down_payment': 0.0},
 {'amount': 45230.0, 'duration': 48.0, 'rate': 0.08, 'down_payment': 4300.0},
 {'amount': 991360.0, 'duration': 99.0, 'rate': 0.08, 'down_payment': 0.0},
 {'amount': 423000.0, 'duration': 27.0, 'rate': 0.09, 'down_payment': 47200.0}]

In [60]:
loans = read_csv('bankLoan')

In [61]:
loans

[{'amount': 100000.0, 'duration': 36.0, 'rate': 0.08, 'down_payment': 20000.0},
 {'amount': 200000.0, 'duration': 12.0, 'rate': 0.1, 'down_payment': 0.0},
 {'amount': 628400.0,
  'duration': 120.0,
  'rate': 0.12,
  'down_payment': 100000.0},
 {'amount': 4637400.0, 'duration': 240.0, 'rate': 0.06, 'down_payment': 0.0},
 {'amount': 42900.0, 'duration': 90.0, 'rate': 0.07, 'down_payment': 8900.0},
 {'amount': 916000.0, 'duration': 16.0, 'rate': 0.13, 'down_payment': 0.0},
 {'amount': 45230.0, 'duration': 48.0, 'rate': 0.08, 'down_payment': 4300.0},
 {'amount': 991360.0, 'duration': 99.0, 'rate': 0.08, 'down_payment': 0.0},
 {'amount': 423000.0, 'duration': 27.0, 'rate': 0.09, 'down_payment': 47200.0}]

In [62]:
import math

def loan_emi(amount, duration, rate, down_payment=0):
   
    loan_amount = amount - down_payment
    try:
        emi = loan_amount * rate * ((1+rate)**duration) / (((1+rate)**duration)-1)
    except ZeroDivisionError:
        emi = loan_amount / duration
    emi = math.ceil(emi)
    return emi

In [63]:
help(loan_emi)

Help on function loan_emi in module __main__:

loan_emi(amount, duration, rate, down_payment=0)



In [64]:
def compute_emis(loans):
    for loan in loans:
           loan['emi'] = loan_emi(
            loan['amount'], 
            loan['duration'], 
            loan['rate']/12, # the CSV contains yearly rates
            loan['down_payment'])

In [65]:
compute_emis(loans)

In [66]:
loans

[{'amount': 100000.0,
  'duration': 36.0,
  'rate': 0.08,
  'down_payment': 20000.0,
  'emi': 2507},
 {'amount': 200000.0,
  'duration': 12.0,
  'rate': 0.1,
  'down_payment': 0.0,
  'emi': 17584},
 {'amount': 628400.0,
  'duration': 120.0,
  'rate': 0.12,
  'down_payment': 100000.0,
  'emi': 7582},
 {'amount': 4637400.0,
  'duration': 240.0,
  'rate': 0.06,
  'down_payment': 0.0,
  'emi': 33224},
 {'amount': 42900.0,
  'duration': 90.0,
  'rate': 0.07,
  'down_payment': 8900.0,
  'emi': 487},
 {'amount': 916000.0,
  'duration': 16.0,
  'rate': 0.13,
  'down_payment': 0.0,
  'emi': 62664},
 {'amount': 45230.0,
  'duration': 48.0,
  'rate': 0.08,
  'down_payment': 4300.0,
  'emi': 1000},
 {'amount': 991360.0,
  'duration': 99.0,
  'rate': 0.08,
  'down_payment': 0.0,
  'emi': 13712},
 {'amount': 423000.0,
  'duration': 27.0,
  'rate': 0.09,
  'down_payment': 47200.0,
  'emi': 15428}]

In [67]:
newFile = open('sample', 'w')

In [68]:
os.listdir()

['.ipynb_checkpoints',
 '.jovianrc',
 '100 Exercises.ipynb',
 'Adobe Photoshop 2021.lnk',
 'AnalysingTabularDataPandas.ipynb',
 'bankLoan',
 'bankLoan.txt',
 'covid_database',
 'data',
 'emis1',
 'LearningDataScience.ipynb',
 'lerningDataSciences.ipynb',
 'Machine learning.ipynb',
 'movies.csv',
 'movies1.csv',
 'orphan.sh',
 'Removed Apps.html',
 'sample',
 'sathyappp']

In [69]:
with open('emis1', 'w') as f:
    for loan in loans :
        f.write('{}, {}, {}, {}, {} \n'.format(loan['amount'], loan['duration'], loan['rate'], loan['down_payment'], loan['emi']))

In [70]:
os.listdir()

['.ipynb_checkpoints',
 '.jovianrc',
 '100 Exercises.ipynb',
 'Adobe Photoshop 2021.lnk',
 'AnalysingTabularDataPandas.ipynb',
 'bankLoan',
 'bankLoan.txt',
 'covid_database',
 'data',
 'emis1',
 'LearningDataScience.ipynb',
 'lerningDataSciences.ipynb',
 'Machine learning.ipynb',
 'movies.csv',
 'movies1.csv',
 'orphan.sh',
 'Removed Apps.html',
 'sample',
 'sathyappp']

In [71]:
with open('emis1') as file:
    lines = file.readlines()
print(lines)

['100000.0, 36.0, 0.08, 20000.0, 2507 \n', '200000.0, 12.0, 0.1, 0.0, 17584 \n', '628400.0, 120.0, 0.12, 100000.0, 7582 \n', '4637400.0, 240.0, 0.06, 0.0, 33224 \n', '42900.0, 90.0, 0.07, 8900.0, 487 \n', '916000.0, 16.0, 0.13, 0.0, 62664 \n', '45230.0, 48.0, 0.08, 4300.0, 1000 \n', '991360.0, 99.0, 0.08, 0.0, 13712 \n', '423000.0, 27.0, 0.09, 47200.0, 15428 \n']


In [72]:
import pandas as pd

In [73]:
pd.read_csv('bankLoan')

amount  duration  rate  down_payment
0   100000        36  0.08       20000.0
1   200000        12  0.10           NaN
2   628400       120  0.12      100000.0
3  4637400       240  0.06           NaN
4    42900        90  0.07        8900.0
5   916000        16  0.13           NaN
6    45230        48  0.08        4300.0
7   991360        99  0.08           NaN
8   423000        27  0.09       47200.0

In [74]:
import urllib.request 

In [75]:
os.listdir()

['.ipynb_checkpoints',
 '.jovianrc',
 '100 Exercises.ipynb',
 'Adobe Photoshop 2021.lnk',
 'AnalysingTabularDataPandas.ipynb',
 'bankLoan',
 'bankLoan.txt',
 'covid_database',
 'data',
 'emis1',
 'LearningDataScience.ipynb',
 'lerningDataSciences.ipynb',
 'Machine learning.ipynb',
 'movies.csv',
 'movies1.csv',
 'orphan.sh',
 'Removed Apps.html',
 'sample',
 'sathyappp']

In [76]:
open('movies.csv')

<_io.TextIOWrapper name='movies.csv' mode='r' encoding='cp1252'>

In [77]:
urllib.request.urlretrieve("https://gist.githubusercontent.com/aakashns/afee0a407d44bbc02321993548021af9/raw/6d7473f0ac4c54aca65fc4b06ed831b8a4840190/movies.csv"
, 'movies.csv')

('movies.csv', <http.client.HTTPMessage at 0x226762c82e0>)

In [78]:

path = 'movies.csv'
path.read_csv()

AttributeError: 'str' object has no attribute 'read_csv'

In [79]:
movie_dataframe = pd.read_csv('movies.csv') 

In [80]:
movie_dataframe

title                                description
0   Fast & Furious               A movie, a race, a franchise
1  The Dark Knight        Gotham, the "Batman", and the Joker
2          Memento  A guy forgets everything every 15 minutes

In [81]:
movie_list = movie_dataframe.to_dict('records')

In [82]:
movie_list

[{'title': 'Fast & Furious', 'description': 'A movie, a race, a franchise'},
 {'title': 'The Dark Knight',
  'description': 'Gotham, the "Batman", and the Joker'},
 {'title': 'Memento',
  'description': 'A guy forgets everything every 15 minutes'}]

In [83]:



movie_dict = movie_dataframe.to_dict()

In [84]:
movie_dict

{'title': {0: 'Fast & Furious', 1: 'The Dark Knight', 2: 'Memento'},
 'description': {0: 'A movie, a race, a franchise',
  1: 'Gotham, the "Batman", and the Joker',
  2: 'A guy forgets everything every 15 minutes'}}

In [85]:
movie_df = pd.DataFrame(movie_list)

In [86]:


movie_df

title                                description
0   Fast & Furious               A movie, a race, a franchise
1  The Dark Knight        Gotham, the "Batman", and the Joker
2          Memento  A guy forgets everything every 15 minutes

In [87]:






movie_df.to_csv('movies1.csv', index =None)

In [88]:
pd.read_csv('movies1.csv')

title                                description
0   Fast & Furious               A movie, a race, a franchise
1  The Dark Knight        Gotham, the "Batman", and the Joker
2          Memento  A guy forgets everything every 15 minutes

In [89]:
movie_df

title                                description
0   Fast & Furious               A movie, a race, a franchise
1  The Dark Knight        Gotham, the "Batman", and the Joker
2          Memento  A guy forgets everything every 15 minutes

In [90]:
movie_df

title                                description
0   Fast & Furious               A movie, a race, a franchise
1  The Dark Knight        Gotham, the "Batman", and the Joker
2          Memento  A guy forgets everything every 15 minutes

In [91]:
import numpy as np
data = np.genfromtxt('bankLoan', delimiter = ',', skip_header = True)

In [92]:
data

array([[1.0000e+05, 3.6000e+01, 8.0000e-02, 2.0000e+04],
       [2.0000e+05, 1.2000e+01, 1.0000e-01,        nan],
       [6.2840e+05, 1.2000e+02, 1.2000e-01, 1.0000e+05],
       [4.6374e+06, 2.4000e+02, 6.0000e-02,        nan],
       [4.2900e+04, 9.0000e+01, 7.0000e-02, 8.9000e+03],
       [9.1600e+05, 1.6000e+01, 1.3000e-01,        nan],
       [4.5230e+04, 4.8000e+01, 8.0000e-02, 4.3000e+03],
       [9.9136e+05, 9.9000e+01, 8.0000e-02,        nan],
       [4.2300e+05, 2.7000e+01, 9.0000e-02, 4.7200e+04]])

In [93]:
pd.read_csv('bankLoan')

amount  duration  rate  down_payment
0   100000        36  0.08       20000.0
1   200000        12  0.10           NaN
2   628400       120  0.12      100000.0
3  4637400       240  0.06           NaN
4    42900        90  0.07        8900.0
5   916000        16  0.13           NaN
6    45230        48  0.08        4300.0
7   991360        99  0.08           NaN
8   423000        27  0.09       47200.0

In [94]:
weight = np.array([1,2,3,4])

In [95]:
weight

array([1, 2, 3, 4])

In [96]:
ans = data@ weight

In [97]:
ans

array([ 180072.24,        nan, 1028640.36,        nan,   78680.21,
              nan,   62526.24,        nan,  611854.27])

In [98]:
np.concatenate(data,ans,  )

TypeError: only integer scalar arrays can be converted to a scalar index

In [99]:
pd.read_csv('bankLoan')

amount  duration  rate  down_payment
0   100000        36  0.08       20000.0
1   200000        12  0.10           NaN
2   628400       120  0.12      100000.0
3  4637400       240  0.06           NaN
4    42900        90  0.07        8900.0
5   916000        16  0.13           NaN
6    45230        48  0.08        4300.0
7   991360        99  0.08           NaN
8   423000        27  0.09       47200.0

In [100]:
weight.transpose()

array([1, 2, 3, 4])

In [101]:
np.transpose(weight)

array([1, 2, 3, 4])

In [102]:
weight

array([1, 2, 3, 4])

In [103]:
a

NameError: name 'a' is not defined

In [106]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [108]:
np.arange(3, 8, 2)

array([3, 5, 7])

In [110]:
np.full([2],2)

array([2, 2])